### ISSUE TITLE
decimal issue

### ISSUE THREAD

**Issue by brickion** [himelbrand/react-native-numeric-input#4]
Relating to #3 

I can no longer type in a number I need. 

For example, type "21" will be prevented, only "2" will be displayed

I can not type 2.50 since `.` is not allowed.

our config:
```
<NumericInput
                    value={this.amount}
                    onChange={(text) => { this.changeAmount(text) }}
                    totalWidth={150}
                    totalHeight={35}
                    minValue={0}
                    maxValue={9999}
                    step={1}
                    iconStyle={{ fontSize: 15, color: '#434A5E' }}
                    inputStyle={{ fontSize: 18, color: '#434A5E' }}
                    valueType='real'
                    borderColor='#C7CBD6'
                    rightButtonBackgroundColor='#C7CBD6'
                    leftButtonBackgroundColor='#C7CBD6'
                  />
```

**Comment by himelbrand** [comment]
Thanks for opening this issue,
but this is not an issue with this package.
I see a few issues in this code, but more code is missing.
and #3 is resolved, since version 1.3.1, so if you're using an older version please update.

about your code:
if you want the value to change you need the render function to trigger on change, meaning you need to use state or state management.

<NumericInput
                    value={this.state.amount}
                    onChange={(amount) => { this.changeAmount(amount) }}
                    totalWidth={150}
                    totalHeight={35}
                    minValue={0}
                    maxValue={9999}
                    step={1}
                    iconStyle={{ fontSize: 15, color: '#434A5E' }}
                    inputStyle={{ fontSize: 18, color: '#434A5E' }}
                    valueType='real'
                    borderColor='#C7CBD6'
                    rightButtonBackgroundColor='#C7CBD6'
                    leftButtonBackgroundColor='#C7CBD6'
                  />
and the onChange function does this:
changeAmount = (amount) => {
   this.setState({amount})
  }

good luck!

**Comment by brickion** [comment]
Please check this screencap movie
https://s3-ap-southeast-2.amazonaws.com/brickion/file/NumberInputIssue.mov

**Comment by himelbrand** [comment]
@brickion I need more information in order to help you.
1) what version of react-native-numeric-input do you have installed?
2) please post the code of this.changeAmount function
3) please post the definition of this.amount
